{{- if and .Values.acl.enabled (not .Values.acl.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "base.fullname" . }}-acl
  labels:
    {{- include "base.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.acl.key | default "rules" }}: {{ .Values.acl.rules | b64enc }}
{{- end }}
