{{- if and .Values.authentication.password.enabled (not .Values.authentication.password.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "base.fullname" . }}-password-auth
  labels:
    {{- include "base.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ default (randAlphaNum 32) .Values.authentication.password.password | b64enc }}
{{- end }}
