{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "base.fullname" . }}-monitor
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  jobLabel: dragonfly
  podTargetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
  selector:
    matchLabels:
      {{- include "base.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: admin
{{- end }}
